### ISSUE TITLE
What does /tf contain?

### ISSUE THREAD

**Issue by zanazakaryaie** [tomas789/kitti2bag#12]
Hello

I'm not sure what does /tf message contains. Does it containt the pose of the left camera obtained with GPS/IMU fusion?

Can I use it as ground truth?

**Comment by tomas789** [comment]
Hi! `/tf` contains relative transformations to all sensors you can find in dataset (including left camera). Besides that, it also contains position of car in the world. Thus you can use it as ground truth.

**Comment by zanazakaryaie** [comment]
I have compared the tf with ground truth provided in odometry section of KITTI. They are different!

**Comment by vkee** [comment]
Yes I have found that too, which is strange as it is based from the GPS/INS data (the source for ground truth). I tried contacting the authors but did not hear back.
