### ISSUE TITLE
Missing information about GPS

### ISSUE THREAD

**Issue by tomas789** [tomas789/kitti2bag#2]
There is few things that are not clear to me:

- Where can I find sections navstat_to_string, gps_mode_to_string, gps_mode_to_string, gps_mode_to_string?
- How to determine if it is GPS fix [see status](http://docs.ros.org/api/sensor_msgs/html/msg/NavSatStatus.html)
- How to determine position covariance matrix correctly [see position_covariance](http://docs.ros.org/api/sensor_msgs/html/msg/NavSatFix.html)? 
- Is it ok to provide `pos_accuracy^2` as diagonal part of `position_covariance` field and set `position_covariance_type` to `COVARIANCE_TYPE_DIAGONAL_KNOWN`?

**Comment by fredbje** [comment]
Did you figure out where to find navstat_to_string and gps_mode_to_string?

**Comment by trigal** [comment]
any news?

**Comment by AbdelrahmanAbdeldaim** [comment]
Did anyone find those mysterious functions?
