### ISSUE TITLE
Example is not working (section: How to run it?)

### ISSUE THREAD

**Issue by AJwgnr** [tomas789/kitti2bag#26]
Hello,

the links for downloading the dataset in the "How to run it?" section are not working:

- `wget http://kitti.is.tue.mpg.de/kitti/raw_data/2011_09_26_drive_0002/2011_09_26_drive_0002_sync.zip`

- `wget http://kitti.is.tue.mpg.de/kitti/raw_data/2011_09_26_calib.zip`

Looking at the links at the KIT website it seems they moved their files (https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_09_26_drive_0001/2011_09_26_drive_0001_sync.zip)

Best,
Alex

**Comment by tomas789** [comment]
Good catch. The readme is updated. Thank you for the contribution!
