### ISSUE TITLE
Could not load module 'pykitti'. Although installed.

### ISSUE THREAD

**Issue by nilseuropa** [tomas789/kitti2bag#47]
```
nils@europa:~/KITTI$ pip show pykitti
Name: pykitti
Version: 0.3.1
Summary: A minimal set of tools for working with the KITTI dataset in Python
Home-page: https://github.com/utiasSTARS/pykitti
Author: Lee Clement
Author-email: lee.clement@robotics.utias.utoronto.ca
License: MIT
Location: /home/nils/.local/lib/python2.7/site-packages
Requires: numpy, pandas, Pillow, matplotlib
nils@europa:~/KITTI$ pip show kitti2bag
Name: kitti2bag
Version: 1.5
Summary: Convert KITTI dataset to ROS bag file the easy way!
Home-page: https://github.com/tomas789/kitti2bag/
Author: Tomas Krejci
Author-email: tomas789@gmail.com
License: UNKNOWN
Location: /home/nils/.local/lib/python2.7/site-packages
Requires: progressbar2, pykitti
nils@europa:~/KITTI$ kitti2bag -t 2011_09_26 -r 0002 raw_synced .
Could not load module 'pykitti'. Please run `pip install pykitti`
```

**Comment by nilseuropa** [comment]
Sorry user error.

**Comment by autoperson** [comment]
> Sorry user error.

I also has the same problem, how can you solve it?

**Comment by yujiazhang777** [comment]
I installed pykitti-0.3.1 but also have this problem.

**Comment by AlterLimbo** [comment]
Try to `import pykitti` directly. And you will find out what's the underlying problem.
Usually, it traces back to `numpy`

**Comment by ulterzlw** [comment]
> I installed pykitti-0.3.1 but also have this problem.

@yujiazhang777 

Try to `import pykitti` directly. And you will find out what's the underlying problem.
Usually, it traces back to `numpy`

**Comment by suyunzzz** [comment]
> > I installed pykitti-0.3.1 but also have this problem.
> 
> @yujiazhang777
> 
> Try to `import pykitti` directly. And you will find out what's the underlying problem.
> Usually, it traces back to `numpy`

hello,i can import pykitti in Ipython,but these is a issue "Could not load module 'pykitti'. Please run `pip install pykitti " now, could u tell me what should i do?

**Comment by chongjeelee** [comment]
maybe only used in python3,not python2

**Comment by WQ-2001-mc** [comment]
检查cv2和numpy是否安装 版本是否匹配

**Comment by ly3106** [comment]
Reference [here](https://github.com/tomas789/kitti2bag/issues/54#issuecomment-1872481534)
