### ISSUE TITLE
Elevation angles do not match the HDL 64 E manual

### ISSUE THREAD

**Issue by geoeo** [tomas789/kitti2bag#49]
In order to calculate the scanline Id one has to use the "algorithm":

1) omega = asin(Z/norm(P))
2) Lookup omega in the UserManual which gives the angle increments for each laser sensor

However when I apply step 1 to the points generated from this python project I get omega values which are outside of the manufacturer supplied threshold of +2 to -24.8 degrees.

This leads me to believe there is a bug when reading the binary velodyne data.

Can anybody confirm or deny this?

Best,
Marc

**Comment by geoeo** [comment]
Seems to be a problem with Kitti / HDL 64 E producing noisy scans

**Comment by mr-abramenko** [comment]
- Check https://github.com/Taeyoung96/kitti2bag/commit/a77c6dffe28fc110dca8f7be6167b5b43cfedbff for finding the ring in a angle based approach
- Check https://github.com/VincentCheungM/Run_based_segmentation/issues/3#issuecomment-452686184 for finding the ring in a non-angle based approach
