### ISSUE TITLE
From /kitti/oxts/gps/fix to /tf

### ISSUE THREAD

**Issue by flpgrz** [tomas789/kitti2bag#56]
Does anybody know where the world reference system of /tf is centered?
I am trying to convert /kitti/oxts/gps/fix (NavSatFix - lat, long, alt) in the /tf world (x, y, z) reference system.

Thanks.

**Comment by valgur** [comment]
The `world` frame origin is the first GNSS fix position. For details see https://github.com/utiasSTARS/pykitti/blob/master/pykitti/utils.py#L133
https://github.com/tomas789/kitti2bag/blob/master/kitti2bag/kitti2bag.py#L58
