### ISSUE TITLE
The ground truth for visual odometry/SLAM

### ISSUE THREAD

**Issue by sunmk2006** [tomas789/kitti2bag#8]
hi, I want to compare the trajectory of my algorithm with the ground truth in the kitti odometry data set, i  need to project my trajectory  into the coordinate system of the left camera after rectification. To verify that the projection is correct or not,replace my trajectory with the output of the GPS/IMU poses in the kitti raw data set,if the conversion is correct, the output should be consistent with the ground truth in the kitti odometry data set. Formula is as follows：
          T_cam0_to_world = kitti.oxts.T_w_imu.dot(inv(kitti.calib.T_cam0_imu))
But the result is not ideal. Can you point out my mistakes and correct them?

**Comment by tomas789** [comment]
Hi, I'm not sure what do you mean with result is not ideal. I'll close this issue right not, because it does not seems to be directly related to `kitti2bag` itself. Feel free to continue in comments.
